### PR TITLE
pre12c compatible version updates to installation and testsuite

### PR DESCRIPTION
**Pull request by dsnz**
a set of updates to installation and testsuite before the upcoming 12c compatible version renaming

### CODE REVIEW

**Comment by jsumners** [comment]
Thank you. I will try to get this reviewed tomorrow.

**Comment by jsumners** [comment]
@dsnz What do you think about putting the backward compatibility shim in its own optional install script?

**Comment by dsnz** [comment]
hi, i do not understand what code you suggest to put in optional install script (I have not yet done the renaming, this is mainly about a tidying up/correction of testsuite so we test the 12c edition later), could you be more specific please ?

**Comment by jsumners** [comment]
I wasn't paying enough attention to what I was reading in the grantsandsynonyms file.

**Comment by dsnz** [comment]
ok, I understand now :smiley:

**Pull request merged**
