### PR TITLE
Begin integrating PLDoc

### PR DESCRIPTION
**Pull request by jsumners**
This PR is going to track my work on integrating PLDoc into the PL/JSON project. Along with that integration, the documentation is being completely overhauled. That includes how the website is built.

Notable changes:

1. Dependency on Grunt is gone. All build procedures are wrapped up in Metalsmith (http://metalsmith.io) and plain old Bash scripts. Everything has an associated `npm` script.
2. The `/doc` directory will be going away.
3. The website will be generated into `/docs`.
4. The API documentation will be generated into `/docs/api`.

As for PLDoc, it is a very limited implementation of JavaDoc. It supports the tags `@param`, `@return`, `@throws` and `@headercom`. The last one, `@headercom`, is unique to PLDoc; it is used to indicate that a comment block is designated as the introductory comment for the source file.

PL/JSON will use the following guidelines for writing PLDoc comments:

1. Only `.decl.sql` files will be parsed for PLDoc comments.
2. Each `.decl.sql` should start with a `@headercom` block.
3. Internal/private variables should be indicated with a simple comment block.
4. An `@throws` for each exception should be included for procedures/functions as appropriate.

The `pljson.type.decl.sql`, `pljson_ext.decl.sql`, `pljson_parser.decl.sql`, and `pljson_value.decl.sql` files in this initial commit show some examples of how to write PLDoc for this project.

I am refraining from including the `/docs` directory in these commits until the last one. Indeed, it should really only be included in a commit during the release process.

@jkrogsboell  @dsnz @boriborm if you guys have any suggestions or comments during this process, please leave them on this PR either as a general comment or a review comment.

Onward to the 2.0.0 release! :)

### CODE REVIEW

**Comment by jsumners** [comment]
@dsnz I think I've done enough on this that it can be merged into `develop`. What do you think? I want to get a new release cut soon.

**Comment by dsnz** [comment]
@jsumners  please allow me time on week end to review

**Comment by jsumners** [comment]
Sure. Not a problem.

**Comment by dsnz** [comment]
@jsumners 
It's impossible of course to review 76 file changes but rather the final generated web documentation.
However I don't know how to access this. The  http://pljson.github.io/pljson  show the old documentation and the  http://pljson.github.io/pljson/api  does not show anything now. Can you give me instructions on how to see on browser the new documentation ?

**Comment by jsumners** [comment]
Look at the Readme in 'site_src'.

**Comment by jsumners** [comment]
You can also just open the index.html in the 'docs' directory.

**Comment by dsnz** [comment]
I can't see the PLDoc generated documentation (the api), I get error "400: Invalid request".

**Comment by jsumners** [comment]
Ah, yes, if you're running `npm run sitedev` then that won't show up. Metalsmith actually removes the `docs` directory and re-creates it (an annoying quirk). Simply re-checkout the `pldoc` branch and open `docs/api/index.html` in your browser.

I don't know of a better way of generating the full documentation and site other than what I have composed in this branch. Everything else gets even more complicated.

With this branch merged, to issue a release one of us would simply do: `npm run release`. This would:

1. Build the website into `docs` using Metalsmith
2. Build the API docs into `docs/api` using PLDOC
3. Create a zip file for attaching to the GitHub release

**Comment by dsnz** [comment]
ok, i will try what you say

I wonder if you can help what will the documentation workflow be

just  .md files serve me fine but if you think we should use a generator, it's ok since you know better
only I would like to know what files to change and how in order to update documentation (the documentation workflow from now on)

I am almost dummy about html, javascript etc (of course I know to use them but I do not specialize in UI and web pages, I don't use npm daily and in fact I dislike such development ...) so I need detailed guidance (for ex. where do I get 'npm' ?)

at this moment the content is the same as in the past, only the display has changed and PLDoc has been introduced for a few types; the content needs updating (including README.md)

**Comment by jsumners** [comment]
`npm` comes bundled with a typical Node.js installation. The easiest way to install Node, but not the easiest way to keep it updated, is to simply download the installer from https://nodejs.org/. Alternatively, and my preferred method given that I do a lot of Node development, is to use `n-install`: https://github.com/mklement0/n-install .

Please note, I'm just using `npm` as tooling here. I'm not using it in a real "development" manner. It's simply keeping Metalsmith installed/updated and running the scripts.

The website source is located in `site_src` and should rarely have to be modified. These are the files that Metalsmith uses to generate the top level files in the `docs` directory.

The actual API documentation is generated from specially formatted comments, known as "docblocks," in the `*.decl.sql` files. For example:

```sql
/**
 * <p>The foo function is a super cool function.</p>
 *
 * @param bar This parameter is used to do special things.
 *
 * @return A string of awesomeness.
 */
function foo (bar in varchar2) return varchar2;
```

As mentioned in the "CONTRIBUTING.md" document, added by this PR, the full description of PLDOC is available at http://pldoc.sourceforge.net/maven-site/docs/Users_Guide/index.html

So, as you're developing and writing your docblocks you can run the `build-apidocs.sh` script to generate the API documentation. Once built, you simply open `docs/api/index.html` in your browser to view the generated documentation. This script will actually download the PLDOC "binary" if you don't already have it.

All of this is developed under the assumption that you are running these scripts in a *nix environment. If you are on Windows, I suggesting using the environment that comes with https://git-for-windows.github.io/ . Its CLI includes everything necessary.

I'm not sure what content you say needs updating. I did update the `README.md`.

**Comment by dsnz** [comment]
well if you say that all we have to do is update the PLDoc content and tags, then it is fine :)
(can I use PLDoc inside example and testuite sql files ?)

I just thought that beyond the api, some more explaining documentation is needed (like a userguide)
organized in some topics/chapters as all projects have
for ex. we need a chapter about the recent introduced handling of numeric values in pljson
(of course this can be in the api but it is somehow lost within the api when it deserves a full chapter)
or for using the dynamic sql and dynamic table capabilities well, or understanding the unicode length limitations etc.
how will these "special" chapters be produced ?

I thought by significantly expanding README.md by including the first doc page and enhancing it with mention of the latest features and introducing links to special-extra doc chapters
this would work fine alongside the PLDoc api (which indeed is a great idea to have documentation within code similar to Javadoc)
and continuing with these I would suggest these chapters go into folder **docs**
and a new folder **docs-api** be used for metalsmith generated content
i.e. current 'docs' be renamed 'docs-api' and a new 'docs' - perhaps with subfolders - be used for the userguide documentation I propose

some examples are in https://github.com/utPLSQL/utPLSQL/tree/develop/docs/userguide
or in https://github.com/grantjenks/sorted_containers/tree/master/docs
or in https://github.com/apache/flink/tree/master/docs

If you agree with the above then no more reviewing is needed and you should merge so I could produce the new documentation (slowly but steadily on weekends; both the userguide and PLDoc)

**Comment by jsumners** [comment]
> I just thought that beyond the api, some more explaining documentation is needed (like a userguide)
organized in some topics/chapters as all projects have
for ex. we need a chapter about the recent introduced handling of numeric values in pljson
(of course this can be in the api but it is somehow lost within the api when it deserves a full chapter)
or for using the dynamic sql and dynamic table capabilities well, or understanding the unicode length limitations etc.
how will these "special" chapters be produced ?

Yes, that sort of stuff is definitely needed. That's why I left the examples directory as-is for now. I completely agree that such things should be written outside of the inline docblocks. The place for these things would definitely be within `site_src/pages`. These pages are not full HTML documents, but rather like Markdown files with minimal HTML markup. Hopefully the pages I have already written provide a clear introduction to how to accomplish this. I also added a readme to `site_src` that attempts to explain how the directory should be used.

My vision is that the root `README.md` is specifically for people interested in the source code of PL/JSON, possibly with the intention of contributing. For general users, the "readme" would be the site that will live at http://pljson.github.io/pljson/ . After everything is merged and released, that website will be served from the content found within the `docs` directory; and the `docs` directory should _never_ be manually edited.

See https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/ for information on the `docs` directory. In short, if compatible files are within that directory, and the repository is configured correctly (which I will do), then GitHub automatically serves that content as a website.

**Comment by dsnz** [comment]
ok I see now, and why a docs folder is needed

I looked at the pages inside site_src/pages and they are html though simple one and I guess I will manage to write such stuff :D 

so please verify that all I need is (I'm on Windows !)
1. node.js for WIndows (n-install is for Linux)
2. PLDoc from sourceforge (this needs JVM which I have already so install should be easy
and I guess I can easily write an equivalent to build-apidocs.sh for Windows)
3. using npm, install metalsmith
4. try all the above and see if they work :)

**Comment by jsumners** [comment]
1. Correct
2. Install https://git-for-windows.github.io/ . It will give a bare-bones "Linux" environment on Windows. Simply use the shell that comes with it, navigate to your PL/JSON project directory, and run ./build-apidocs.sh (or `npm run gendocs`). But if you really want to make an equivalent Windows specific version, go for it.
3. That command would simply be `npm install`. npm will read the information in `package.json` and take care of everything.

**Comment by dsnz** [comment]
ok, I have all installed and seem to work

I don't understand what metalsmith does exactly, the html in docs are almost the same as those in site_src sans some js and stylesheets loaded at start and end,
and still the user has to use class=within html (for ex. <code class="hljs sql">)

what available stylesheet classes or formatting options do I have ?

**Comment by dsnz** [comment]
ok, I have all installed and seem to work

I don't understand what metalsmith does exactly, the html in docs are almost the same as those in site_src sans some js and stylesheets loaded at start and end,
and still the user has to use class=within html (for ex. ```<code class="hljs sql">```)

what available stylesheet classes or formatting options do I have ?

**Comment by jsumners** [comment]
The benefit is that all of the boilerplate `<head>` and common resources (js, styles, etc.) don't have to be added to every file within `site_src/pages`. It allows us to focus on writing the content.

Aside from the minimal styling of the basic elements in `site_src/assets/style.css`, the only extra styles are from https://highlightjs.org/ . So those are what you'd be able to use with `code` elements.

**Comment by dsnz** [comment]
ok, all clear, so I will do my html/css practice in the next months :)

before we close this issue, one last thing that annoys me
when I click on index.html (or any other html) so that I can view it inside chrome, I wait for a long time for no reason (about 90 sec) but then I see the page
if I click on X, in order to stop the loading then I can see the page again and on reload the page loads instantly

from my little web development knowledge I used Chrome inspect and got messages that the network files (js and css) were not loaded
perhaps the urls for these files are wrong ?

**Comment by jsumners** [comment]
I think the CDN is being slow. I noticed the same thing at james.sumners.info a few days ago.

**Pull request merged**
