### PR TITLE
Fix for issue #69 (pljson_printer prints invalid number if very small)

### PR DESCRIPTION
**Pull request by nyg**
I'm providing a fix for the issue #69 I opened a few weeks ago.
I've also added a unit test with it.

### CODE REVIEW

**Comment by dsnz** [comment]
@jsumners 

Hi, sorry for being late. By next week I will have my PR.

Fix for #70 is almost complete and was about to do validation testing and then work for #69.
It's good to see fix here. I will incorporate it with some changes needed to include the logic for #70.
Thank you for being patient. It's a stressy time this.

**Comment by jsumners** [comment]
@dsnz I'm just asking you to review this PR and indicate if it "Looks Good To Me" for merging.

**Comment by dsnz** [comment]
@jsummers

oh, sorry, I saw the message about "approved changes" and thought the PR was merged already !

I checked the request changes and I can say it's a great job and yes it "Looks Good To Me" 👍 
(I also approved thru Github)

**Comment by jsumners** [comment]
Thank you for the patch @nyg. I'm hoping we can get a 2.0 release out in the near future. But you can always run the `develop` branch if you are comfortable with that.

**Pull request merged**
