### PR TITLE
Do not advertise commercial software

### PR DESCRIPTION
**Pull request by d-javu**
There are two identical ```example.pdf``` files in the testsuite directories that advertise a commercial product.
Unless the project is making millions from this, I suggest we remove them.

### CODE REVIEW

**Comment by dsnz** [comment]
Hi,

I'm on the road now unfortunately and can't check this immediately.

Definitely we don't make millions, not even a cent ! :D

I'm sorry I didn't notice the content of the pdf before (just tested code
worked).
If I remember well some example.pdf (s) are used in example(s) and test
code. I will have a look at it soon as I can and I will replace with
another more suitable example.pdf (you can also suggest a good example.pdf).

**Comment by d-javu** [comment]
I didn't think to look for that, but a

```
grep -r example.pdf .
```
at the top level finds nothing relevant.

```
grep -r pdf .
```
finds use of ```utl.save_file()``` in the test dirs, using ```w_blob1.pdf``` and ```w_blob2.pdf``` together with ```DATA_PUMP_DIR```
I think the two ```example.pdf``` files can be safely removed.

**Comment by dsnz** [comment]
Then I will merge this as soon as I am able. Thanks  you again.

**Comment by dsnz** [comment]
@d-javu 
could you kindly check also **ex13.sql** which creates some binary file(s)
and also the **testsuite/pljson_base64.test.sql** and **testsuite-utplsql/utplsql_pljson_base64_test.sql**
which again create some binary files(s)
that their content is appropriate ? (gif or jpg or pdf or ...; I still have this lingering thought that one of them creates the example.pdf file you deleted and should be replaced)
due to some personal issues I will be able to check them some days later while you seem to be ready for updates and contributing to the project

**Comment by d-javu** [comment]
Thanks for asking, it forced me to investigate further, and to discover that I had botched the base64 encoded data in example 13. I'll rectify, and send a PR.

The ex13.sql contains data for a very appropriate .gif file.
I suggest it is left as an easter egg, so inquiring minds can decode and view it. :smile:

You are absolutely correct that the base64 test contains the same pdf file, but it is only handled internally, not written to disk.

**Comment by dsnz** [comment]
great! (and I'm curious now about that gif, I have forgotten it's content
long time ago :D)
that pdf of the base64 file should be changed even if handled internally, I
take note to do this sometime in future

I will merge all your PR(s) until tomorrow

**Pull request merged**
