### PR TITLE
utPLSQL tests

### PR DESCRIPTION
**Pull request by Pazus**
This is how it might look like.
Migrated parser tests to the framework. The output is:
```
core
  pljson_parser tests
    Test number start with 0-9 [.003 sec]
    Test digits in fraction [.004 sec]
    Test digits in exp [.004 sec]
    String tests [.005 sec]
    Boolean tests [.004 sec]
    Null tests [.004 sec]
    Test unexpected char line 226 [.004 sec]
    Unicode char test - on UTF8 databases [.004 sec]
    Object member tests [.004 sec]
    Object testing [.005 sec]
    Test duplicates [.004 sec]
    Parser testing [.008 sec]
    Lexer String ending test [.004 sec]
    2016-04-12 Test for issue issue #37 by mbodorulin proposed by Borodulin Maxim github.com/boriborm [.01 sec]
 
Finished in .077099 seconds
14 tests, 0 failed, 0 errored, 0 disabled, 0 warning(s)
```

You can migrate all the other tests quickly, this one took about 30 mins. But if you define a CI building your framework on each commit/PR you can fail the build if any test is broken. Also you'll get the coverage rate after you migrate all the other tests.

### CODE REVIEW

**Comment by dsnz** [comment]
hi, thank you
I want to do a quick test first (and also try a few things) by downloading utPLSQL (I don't want to create new git repositories now) using the equivalent urls

https://github.com/utPLSQL/utPLSQL/archive/master.zip
https://codeload.github.com/utPLSQL/utPLSQL/zip/master

and all I get is 186 bytes ... (many other repositories on github, including our own, download normally)
it seems github is not supporting you :)

can you please send me somehow the master.zip ?

**Comment by Pazus** [comment]
Download it from the Release page. We propagate version numbers to the build artifacts or simply check it out with Git.

**Comment by Pazus** [comment]
https://github.com/utPLSQL/utPLSQL/releases

**Comment by jgebal** [comment]
Even better - https://github.com/utPLSQL/utPLSQL/releases/latest

**Comment by jgebal** [comment]
@Pazus as part of that PR, you could build a CI/CD with Travis and utPLSQL, just like it is done in [utPLSQL-demo-project](https://github.com/utPLSQL/utPLSQL-demo-project)

**Comment by jgebal** [comment]
@dsnz, It's quite easy to replicate the CI/CD setup to your project with Travis/SonarCloud&utPLSQL.
A minimal setup of env variables is needed on Travis and you get a continuous testing and code quality check for free.

**Comment by jsumners** [comment]
Yeah, I looked at the demo project yesterday. I'm surprised at how easy it looks to setup Travis for testing.

Is it possible to test against 12c in addition to 11g?

**Comment by jgebal** [comment]
With Travis it's not trivial due to space limits (12C is huge).
What we did in utPLSQL is we created private Docker images for the project that contain a slim version of 12.1 and 12.2 so our CI runs on 3 different DB versions for each commit.
Docker images need to be private due to Oracle licensing -> cannot redistribute their products.

**Comment by jgebal** [comment]
If you're interested, perhaps we can help you with 12c setup for Travis.
I guess you need to test new version of pljson on 12c (naming changes in develop branch)

**Comment by jsumners** [comment]
@jgebal that's correct. I am certainly welcome for any assistance on setting it up. I want to wait to really dig into this until after my documentation re-org is merged into develop.

**Comment by dsnz** [comment]
@Pazus @jgebal 
some notes from my quick familiarization experience with utPLSQL

1.
installation produces quite many error messages
for example, at the very beginning the installation log is

```
Installing utplsql framework
SP2-0317: expected symbol name is missing

Session altered.


Session altered.


Type created.


Type created.


SP2-0816: Type created with compilation warnings


Type body created.
```

however, the installation validation at the end is fine (I guess a recompile is done at this moment) and the final state of the installation is valid indeed

I think this is scary :) for a new user and there should be a mention of error messages appearing or disable all such messages altogether and leave alone the validation message

2

a. the coverage capability is how they say all the money :) (can you make something similar for python, Java, ... ? :D) 
but it shows the html on screen (I used simple html listing),
I had to spool it a second time and even edit the final spool file to remove some test messages in order to get a valid html to view
is there an option that produces automatically a good html file ?
(I think there should be and probably I just don't know it since I have not read extensively the documentation yet)

b. the final html includes calls to github for js code etc.
I think (continuing a.) that it should produce a standalone web page on the user's file system

**Comment by dsnz** [comment]
@Pazus

I'd like to merge the pull request, (we will extend and use it at the next opportunity)
the example is very good though it has some issues with mangled unicode inside test strings (we will fix them)
however I will kindly ask a few simple changes in order to blend best with our naming conventions

1. rename the folder from test2 to testuite-utplsql
2. rename the .pck test package to pljson_parser_test.sql (and similary rename the package inside to pljson_parser_test)

after these changes, I will merge the request

**Comment by jgebal** [comment]
@dsnz please use utplsql-cli project or utplsql-sql-cli  for running ut from command line.
It's worth reason the doc. It's not perfect but should give an insight.

**Comment by Pazus** [comment]
@dsnz thank you for the feedback! Will take a look at the reported issues.

On coverage reporting, I believe that HTML reported is the less used one! You should not integrate it into you CI/CD pipelines, it's only for manual looking through. For CI/CD you should use special types of reporters, like sonar reporter and consume coverage results using specialized tools like Sonarqube or coveralls. Have you seen our projects at Sonarqube and coveralls?
https://coveralls.io/github/utPLSQL/utPLSQL?branch=develop

It's very easy to implement such native reporting using the framework. For our own repo decrease in coverage rate is one of the reason for PR to be declined.

Here is sonar:
https://sonarcloud.io/dashboard?id=utPLSQL%3AutPLSQL%3Adevelop

**Comment by Pazus** [comment]
We've just release version 3.0.2  which faces most of you issues I guess.

**Comment by jgebal** [comment]
3.0.2 resolves issues with install script readability

**Comment by dsnz** [comment]
thank you !
install is much better (though still a few type errors)
and spool output is again much cleaner (though still some way to make automatically a simple or complete web page would be nice)

please don't rush to make new changes, I'm fine :)

**Comment by Pazus** [comment]
I've addressed the comments.

**Comment by dsnz** [comment]
hello,
I had already installed with some fixes your tests in my local git repo and since github often says that pull requests cannot be merged if there are already changes on github for same files and makes my life very difficult
I decided to push my commit and will abandon your 2 commits
thank you again for informing us about utplsql

**Comment by jsumners** [comment]
@Pazus @jgebal I'm sorry your contribution didn't get incorporated correctly. @dsnz did give you guys credit in his changes, though.

@dsnz what you're describing is a merge conflict. Clearly, this occurs when two people (or just two branches) have made changes to the same file in such a manner that _git_ cannot determine which change "wins". Given that you are an owner of this project, here's what should have happened to facilitate this PR being incorporated cleanly:

1. You should be working directly from this repository. You no longer need to work from `dsnz/pljson`. You can work with a local `pljson/pljson` clone just as you see me doing.

2. Either wait until the changes in the PR are updated by the original authors so that they can be incorporated cleanly prior to starting your work on based on them, or add their remote so that you can work against their code:

    ```
    [pljson/pljson] (develop) > git remote add pazus https://github.com/Pazus/pljson 
    [pljson/pljson] (develop) > git checkout -b utplsql-testing
    [pljson/pljson] (utplsql-testing) > git merge pazus utplsql-tests-draft
    [pljson/pljson] (utplsql-testing) > # make your changes
    [pljson/pljson] (utplsql-testing) > git checkout pazus/utplsql-tests-draft
    [pljson/pljson] (utplsql-tests-draft) > git pull # get any new changes
    [pljson/pljson] (utplsql-tests-draft) > git checkout utplsql-testing
    [pljson/pljson] (utplsql-testing) > git merge pazus utplsql-tests-draft # incorporate those changes
    [pljson/pljson] (utplsql-testing) > git push -u origin utplsql-testing # push new branch to our repo
    ```

    If this were done, you could have still closed this specific PR and merged your "utplsql-testing" branch into the "develop" branch. That way, the Git log and the GitHub tracking would still show where the changes came from. You can see this very situation done successfully at https://github.com/pinojs/pino/pull/168#issuecomment-273642368

**Comment by dsnz** [comment]
@jsumners 

it's github that's strange many times, with classic git (!) I have no such merge issues (the changes are on different lines so there should be no conflicts)

about 1. I am thinking it a long time already, normally it's best if each contributor has his own repository
about 2. a. well waiting.. is not practical, I had already worked on the code
b.  adding their remote (9 commands and new branches) shows git mastery 👍  but it's way too much for a few simple changes

**Comment by Pazus** [comment]
Is there a way we may help you with our changes?

**Comment by dsnz** [comment]
@Pazus 
your changes are ok, if anything is needed in the other utplsql tests that will be implemented, we know where to ask help :)
thank you again

**Pull request closed without merging**
