### PR TITLE
Unicode strings in json without ORA-6502 errors

### PR DESCRIPTION
**Pull request by dsnz**
Set of changes to allow big unicode strings in json output without ORA-6502 errors.
Character buffers are 32767 bytes but stored text and loops are limited to 5000 CHAR(s)
(more than enough to store text at 4 bytes/CHAR or store the \uxxxx escaped representation at 6 bytes/char).
Intended to be used mainly with CLOB parameters or VARCHAR2 limited to 5000 CHAR(s).

### CODE REVIEW

**Comment by dsnz** [comment]
Hello,

my test procedure (updated a bit for testing the new fork) is

create or replace procedure json_test as
test_clob_json json;
test_clob clob;
json_clob clob;
test_buf VARCHAR2(200) := 'αβγδεζηθικλμνξοπρστυφχψωΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩάέήίόύώϊϋΆΈΉΊΌΎΏ';
test_var VARCHAR2(3900 CHAR);
test_var_json json;
json_var varchar2(32767);
i number;
k number;
begin
dbms_lob.createtemporary(test_clob, TRUE, dbms_lob.SESSION);
dbms_lob.trim(test_clob, 0);
k := length(test_buf);
i := 0;
while i < 100000 loop
dbms_lob.writeappend(test_clob, k, test_buf);
i := i + k;
--dbms_output.put_line(i);
end loop;
i := 0;
while i < 60 loop
test_var := test_var || test_buf;
i := i + 1;
--dbms_output.put_line(i);
end loop;

test_clob_json := json();
test_clob_json.put('publish', true);
test_clob_json.put('issueDate', to_char(sysdate, 'YYYY-MM-DD"T"HH24:MI:SS'));
test_clob_json.put('subject', json_value(test_clob));

test_var_json := json();
test_var_json.put('publish', true);
test_var_json.put('issueDate', to_char(sysdate, 'YYYY-MM-DD"T"HH24:MI:SS'));
test_var_json.put('subject', test_var);

dbms_lob.createtemporary(json_clob, true, dbms_lob.SESSION);
dbms_lob.trim(json_clob, 0);
test_clob_json.to_clob(json_clob);
/* ignore, local procedure, not Oracle available
util_pkg.clob_to_os_utf(json_clob, 'json_test.json', 'TEMP_HOME');
*/

dbms_lob.freetemporary(test_clob);
dbms_lob.freetemporary(json_clob);

json_var := test_var_json.to_char();

end;

I can verify that the fork passes the test for the clob part.

However

a. the fork is nicely using CHAR sizes and is well written but I am afraid that there are issues with the VARCHAR2 version of the api now (uncovered by the second test) because the routines use a buffer of 8191 chars = 32764 bytes max and if escapeString is used then the escaped repr may explode to 8191 * 6 > 32764
this is the reason i restricted my solution to just 5000 chars "everywhere" and I even changed the 'if' in add_clob to "if(length(str) > 5000 - length(buf_str)) then"
(I think this is a very useful library and sometime the source should be refactored with shorter code and global variables for BUFFER_SIZE and AMOUNT and a thorough review that all cases are covered)

b. I wanted to push a merge as contribution to this project ...
please accept my merge and then change it :) :)

**Comment by boriborm** [comment]
Well. All right. escapeString with buffer length 8191 not work correct when result escaped string more than 8191. I agree, than it need set varchar2 variables used in functions of json_printer packages and returned varchar2, set length to 5000 chars. But why you replace add_escaped_string_to_clob, where no problems with length 8191, to add_to_clob (...., escapedString(...)), where this problem is it? I disagree.
We have String variables more then 32767 bytes (chars) and add_escaped_string_to_clob work fine. Clob not have max length 32767 bytes or 8191 chars!

Procedure add_to_clob operate with bytes, not chars. It work correct with any byte length of chars.

You tested my last committed variant in my fork with json_printer procedures where use clob parameter? I thing it will work fine, but i can't test it. My database set to 1 byte char mode...

**Comment by dsnz** [comment]
Hello,

even if your database is 1 char the test procedure should still work, it is self-contained, try it

about 'add_to_clob (...., escapedString(...))' yes you are somehow right...

I thought about this carefully (I had worked with past versions of pljson and I did not know this new procedure which was created to take care of big sizes)
but I reasoned if we fix size problems for all then we do not need this and we can do with just one 'escapeString()' rather than have two versions doing the same thing
in the code there is always a loop which takes the clob content in 5000 char pieces which can be handled very well with escapeString (with 32767 bytes buffer) and escapeString is still useful for sites that wish to use up to 32767 single-byte chars

**Comment by boriborm** [comment]
Use functions returning varchar2 is bad solutions. Json data may be
{
 "tag1":"<escaped string with 5000 chars>",
 "tag2":"<escaped string with 5000 chars>",
 ...
 "tag6":"<escaped string with 5000 chars>",
 "tag7":"<escaped string with 5000 chars>"
}
or
{
 "tag1":"<escaped string with 500 chars>",
 "tag2":"<escaped string with 500 chars>",
 ...
 "tag69":"<escaped string with 500 chars>",
 "tag70":"<escaped string with 500 chars>"
}

and then what? Full json length be more than 8191.
Use functions returning varchar2 is particular solution, when we need make short json and we know that json will be less then 8191.

I strongly recommended use procedures with clob parameters :)

**Comment by dsnz** [comment]
I totaly agree with you (and we use clob here) !

[but the api already exposes a varchar2 version and some effort should be made to exhaust it's usefuleness; my idea is an api should work well as much as possible based on the constraints of Oracle]

**Pull request closed without merging**
