### PR TITLE
test updates

### PR DESCRIPTION
**Pull request by dsnz**
streamline pljson_table test
update utplsql tests
minor changes in test banner text

### CODE REVIEW

**Comment by dsnz** [comment]
@d-javu 
Hi, I have just made a new commit that fixes the issue
please don't criticize the method I used (execute immediate vs distinct block as in your code) because I want to have same code with utplsql (which has it's own esoteric problems - ! - with an insert into a non existing table and which are not fixed by a new block, and for which I will soon create a new issue in their project page)

**Comment by d-javu** [comment]
I've just checked, and it works for me.

My sympathies on the utPLSQL issues.
As someone who has written their own simple (at least it started that way) PL/SQL unit testing framework, directed by ```make``` I'm quite sure that there are always many things that can be improved in the testing frameworks.

**Comment by dsnz** [comment]
Hi,

I'm interested about your framework, especially the use of "make" :)
I always look at other software for ideas.
Can you please send me this framework code or point me to some
repository/web page where I can find it ?

**Comment by d-javu** [comment]
I'll send you an email :)

**Pull request merged**
