### PR TITLE
12c friendly version; rename of packages and types to 'pljson_'

### PR DESCRIPTION
**Pull request by dsnz**
minor changes in format/spaces and comments
respective changes and enhancements/fixes in testsuite
and in install/uninstall/grantsandsynonyms scripts

because recently I have access only to a new 12c database without software utilizing pljson,
I cannot test for sure backward compatibility with existing applications,
I hope @jsumners and @boriborm can do some tests and report here

### CODE REVIEW

**Comment by jsumners** [comment]
My work is in the process of moving to 12c. So I should be able to test it soon-ish.

**Comment by dsnz** [comment]
Hi, that would be nice (so we know if code using packages and types named with 'json_' still works).

I just noticed you tagged the last commit with 1.0.6. In that case we should update the pljson_parser.getversion() function to return 'PL/JSON v1.0.7' or perhaps 'PL/JSON v1.1.0'.
I had taken the liberty to make it return 'PL/JSON v2.0.0' in this pull request since I had no idea and many code changes had been made.
I'm keeping this request and not merging until there is feedback from everybody.

**Comment by jsumners** [comment]
This 12c patch is going to be 2.0.0. So leave it there. Switching to semver with this major overhaul.

**Comment by jsumners** [comment]
I haven't forgot about this pull request. We have someone tasked with installing it and testing it in our 12c environment. He just hasn't been able to get to it yet. Should be relatively soon.

**Comment by jsumners** [comment]
Here's the result of the unit tests:

image

**Comment by dsnz** [comment]
Hi,

seems fine, the 2 failed tests are probably due to not using the NLS_LANG shown in the warning message at start
have you tried any applications that make use of the pljson library ?

(if all ok and we merge this, I will have to make an extra pull request to include the last code change by Vladislafff as it is not mergeable)

**Comment by jsumners** [comment]
We should consider making those tests pass in any language, or at least skip and issue only a warning.

Go ahead and merge in the changes to your branch and push them up:

```sh
$ git remote add upstream git@github.com:pljson/pljson.git
$ git pull upstream develop
$ git mergetool # resolve conflicts
$ git push
```

**Comment by dsnz** [comment]
Hi,

unfortunately Oracle does not allow changing characterset within session (yet) so there is no other way to do this test but only by setting the characterset before connection, if it was possible I would have done already

to skip the test is a good idea indeed, but it is not easy and reliable to get the session characterset within pl/sql (and perhaps it is even possible only on 11+), i will explore this path and if possible I will do it but still issue a warning that the testsuite is not complete

I will do the merges within the coming week, just in case another update pops up in the meantime

**Comment by jsumners** [comment]
Don't worry about changing the tests for this PR; I just mentioned it up as a future idea since it came up.

I'm working on re-organizing documentation, but I won't be pushing it up until we get your change merged. In fact, I'm going to hold off on *all* PRs until this one is merged.

When you do get a chance to push the updates, take the time to adjust the PR to target the 'develop' branch.... 

~sigh~ I decided to check if that's really possible before clicking the "Comment" button. It's not, https://github.com/isaacs/github/issues/18 . Very, very, disappointing.

Since that is the case, I'm closing this pull request. That doesn't change anything, though. I still want this change set merged in before any other new PRs are accepted. Please create a new PR for these changes and target the 'develop' branch.

**Comment by dsnz** [comment]
I work on a develop branch too so it is easy to push new updates to this pull request,
so perhaps let's keep this open rather than opening an extra one later for same reason
I will try to push in as few days as possible so no anxiety

**Comment by jsumners** [comment]
The issue is that the "merge pull request" button on this PR will merge this PR into the 'master' branch. I don't like having to create a new PR to fix this either, but GitHub evidently don't feel like making it possible to change the target.

**Comment by dsnz** [comment]
yes, now I noticed this detail ! but how did it happen ??
I had certainly opened this pull request targeting pljson/develop ...

ok, I close this now and will open a new one in the next days

**Pull request closed without merging**
