### PR TITLE
new schema and function name overriding

### PR DESCRIPTION
**Pull request by brizjin**
Hello!
It easy to understand in use function name overriding.
And I add one more schema for converstion from here: http://stefan-armbruster.com/index.php/12-it/pl-sql/12-oracle-xml-and-json-goodies

### CODE REVIEW

**Comment by jsumners** [comment]
Why have you replicated the `to_clob` procedure as a function? And why is it ignoring pretty much every parameter?

**Comment by brizjin** [comment]
You can use to_clob functoin in this construction:
`msg := json_ml.xml2json(v).to_clob;`
instead of:
```
declare
    my_clob clob;
begin
    dbms_lob.createtemporary(my_clob, true);
    self.to_clob(my_clob);
    msg := my_clob;
end;
```
Yes, about parameters i forgot, but get it back it last commit (fc6bae7)

**Comment by jsumners** [comment]
Yes, your last commit added the parameters to the function declaration, but the actual implementation does not consider them at all. In other words, if one were to do:

```sql
some_json.to_clob(spaces => true, chars_per_line => 80)
```

The result would be absolutely no different than if they had done:

```sql
some_json.to_clob()
```

I appreciate that this may be a useful function. But,

1. It seems like a completely separate addition than the new XML stylesheet (i.e. should be a separate PR). Unless I'm just missing the part of the PR where this function is used to implement the XML stylesheet addition.
2. It needs to honor the function signature.

**Comment by brizjin** [comment]
If I correct understand about parameters, I add them.
And yes you are right that this is two separate additions. I use them like this, to have two different convertions by to different stylesheet:
```
    msg1 := json_ml.xmlgen2json(t);
    msg2 := json_ml.xml2json(t).to_clob;
```
You are rigth about it should be a way how to choose stylesheet when we call `json_ml.xml2json(t).to_clob` May be now it can be used like this, and later can be implement widly.

**Comment by jsumners** [comment]
That's much closer. You should use the named parameters style as is used in the procedure:

```sql
self.to_clob(my_clob, spaces => spaces, chars_per_line => chars_per_line, erase_clob => erase_clob);
```

**Comment by boriborm** [comment]
I think use function for clob is not seriously.

```
declare
    my_clob clob;
begin
    dbms_lob.createtemporary(my_clob, true);
    json_ml.xml2json(v).to_clob(my_clob);
    msg := my_clob;
    dbms_lob.freetemporary(my_clob);
end;
```
What type of `msg`? varchar2? Use to_clob for varchar2 can get mistakes. You need use to_char. Clob may be more than 32767 1-byte chars or more than 8000 4-byte chars. For to_char it raise application exception of json_printer, not oracle exception ORA-06502.
And where is in code freetemporary of clob?

After change we can write:
```
declare
    my_clob clob;
begin
    my_clob:=json_ml.xml2json(v).to_clob();
    msg := my_clob;
    dbms_lob.freetemporary(my_clob);
end;
```
This we need free temporary clob, but it is not obviously in code because we not see temporary clob creation, and we can write:
```
declare
    my_clob clob;
begin
    my_clob:=json_ml.xml2json(v).to_clob();
    msg := my_clob;
end;
```
I think it is not right.

**Pull request closed without merging**
