### PR TITLE
Performance improvements for string-based path API

### PR DESCRIPTION
**Pull request by asfernandes**
Complements #204

### CODE REVIEW

**Comment by asfernandes** [comment]
@dsnz since I cannot create a pull request based on a pull request, it has the same #204 commits plus 7542078 reverting 3296d2e.

**Comment by dsnz** [comment]
Hi
I noticed that it has the same changes. Don't worry about this.
Please allow me sometime over the weekend to check thoroughly the changes in the new ```put_internal_path``` vs original ```put_internal``` code, even some more days as it is summer but I feel it will be ok.
Talk again in a week.

**Comment by dsnz** [comment]
(now that I merged the previous pull request, perhaps you can simplify this pull request to only the necessary changes but if not no worry as I said)

**Comment by asfernandes** [comment]
Github does not allow me to rebase this PR nor create another one. The only new commit here is https://github.com/pljson/pljson/commit/75420783da727008a489f9a91001224baa9c3c0c.

You can rebase the PR when merging.

**Comment by dsnz** [comment]
it's fine, I'm sure it will go ok
talk again next week
:)

**Comment by dsnz** [comment]
closed as a new pull request will be made combining #205 and #206

**Comment by asfernandes** [comment]
> it's fine, I'm sure it will go ok
> talk again next week
> :)

I'm sorry but I was not able to look at this in work again. And personal time is scarce as my daughter born.

**Comment by dsnz** [comment]
@asfernandes 
it's okay, this is open source and free and not our job or life
we expect more contributions from you and congratulations on the birth of your daughter

**Pull request closed without merging**
